CREATE TABLE Student( 
	Id INTEGER PRIMARY KEY AUTOINCREMENT, 
	Name VARCHAR(255) NOT NULL, 
	Email VARCHAR(255) NOT NULL, 
	Year INT NOT NULL, 
	VolHours VARCHAR(255) NOT NULL, 
	Gender VARCHAR(255) NOT NULL, 
	CONSTRAINT StudentPk UNIQUE(Id,Email)
);
CREATE TABLE Teacher(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(255) NOT NULL,
	Degree VARCHAR(255) NOT NULL,
	YearsTaught INT NOT NULL,
	CONSTRAINT TeacherPk UNIQUE(Id)
);
CREATE TABLE CurrentClasses(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(255) NOT NULL,
	Grades VARCHAR(255) NOT NULL,
	TeacherId INT NOT NULL,
	StudentId INT NOT NULL,
	CONSTRAINT FK_CurrentClasses_TeacherId_2_Teacher_Id FOREIGN KEY(TeacherId) REFERENCES Teacher(Id)
	CONSTRAINT FK_CurrentClasses_StudentId_2_Student_Id FOREIGN KEY(StudentId) REFERENCES Student(Id)
);
CREATE TABLE PastClasses(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(255) NOT NULL,
	FinalGrades VARCHAR(255) NOT NULL,
	GPA FLOAT NOT NULL,
	StudentId INT NOT NULL,
	CONSTRAINT PastClassesPk  UNIQUE(Id)
	CONSTRAINT FK_PastClasses_StudentId_2_Student_Id FOREIGN KEY(StudentId) REFERENCES Student(Id)
);
CREATE TABLE Extracurriculars(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Sports VARCHAR(255) NOT NULL,
	Competitve VARCHAR(255) NOT NULL,
	Leisure VARCHAR(255) NOT NULL,
	StudentId INT NOT NULL,
	CONSTRAINT ExtracurricularsPk UNIQUE(Id)
	CONSTRAINT FK_Extreacurriculars_StudentId_2_Student_Id FOREIGN KEY(StudentId) REFERENCES Student(Id)
);
CREATE TABLE Behaviour(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Demerits INT NOT NULL,
	GoldStars INT NOT NULL,
	Scaling INT NOT NULL,
	StudentId INT NOT NULL,
	CONSTRAINT FK_Behaviour_StudentId_2_Student_Id FOREIGN KEY(StudentId) REFERENCES Student(Id)
);
